name: Lint Code
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: ["16"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install
      
      - name: Lint
        run: yarn run lint
